baseURL = 'https://test.tyza66.top'
languageCode = 'zh-cn'
title = 'tyza66的博客'
theme = 'PaperMod'

[params]
  author = 'tyza66'
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

# 你的栏目菜单
[[menu.main]]
  identifier = 'home'
  name = '首页'
  url = '/'
  weight = 10

[[menu.main]]
  identifier = 'opensource'
  name = '开源演示'
  url = '/open_source_demonstration/'
  weight = 20

[[menu.main]]
  identifier = 'codetalk'
  name = '码上杂谈'
  url = '/code_talk/'
  weight = 30

[[menu.main]]
  identifier = 'event'
  name = '忆往特'
  url = '/event/'
  weight = 40

[[menu.main]]
  identifier = 'fantasy'
  name = '范特西'
  url = '/fantasy/'
  weight = 50

[[menu.main]]
  identifier = 'about'
  name = '关于'
  url = '/about/'
  weight = 60