baseURL = 'https://www.tyza66.top'
languageCode = 'zh-cn'
title = 'tyza66的博客'
theme = 'PaperMod'

[params]
  author = 'tyza66'

[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

[markup.goldmark.renderer]
  unsafe = true

[params.profileMode]
  enabled = true
  title = "tyza66的博客"
  subtitle = "技术分享、日常思考"
  imageUrl = "https://github.com/tyza66.png"
  imageWidth = 120
  imageHeight = 120

[[menu.main]]
  identifier = 'home'
  name = '首页'
  url = '/'
  weight = 10

[[menu.main]]
  name = '技术分享'
  url = '/technology_sharing/'
  weight = 20

[[menu.main]]
  identifier = 'opensource'
  name = '开源演示'
  url = '/open_source_demonstration/'
  weight = 30

[[menu.main]]
  identifier = 'codetalk'
  name = '码上杂谈'
  url = '/code_talk/'
  weight = 40

[[menu.main]]
  identifier = 'event'
  name = '忆往特'
  url = '/event/'
  weight = 50

[[menu.main]]
  identifier = 'fantasy'
  name = '范特西'
  url = '/fantasy/'
  weight = 60

[[menu.main]]
  identifier = 'about'
  name = '关于'
  url = '/about/'
  weight = 70